packages:
  - scripts/*
  - internal/*
  - apps/*
catalog:
  "@manypkg/get-packages": ^2.2.2
  "@clack/prompts": ^0.8.2
  "cac": ^6.7.14
  "execa": ^9.5.1
  "find-up": ^7.0.0
  "sass": ^1.78.0
  "typescript": ^5.6.2
  "unbuild": ^3.0.0-rc.11

  "vite": ^6.0.0
  "vue-tsc": ^2.1.10
