// Auto generated contend
// DO NOT EDIT THIS FILE MANUALLY

export const PackageList = [
  {
    name: "@malphite/core",
    path: "packages/frontend/core",
    workspaceDependencies: [],
  },
  {
    name: "@malphite-tool/cli",
    path: "tools/cli",
    workspaceDependencies: ["tools/utils"],
  },
  {
    name: "@malphite-tools/utils",
    path: "tools/utils",
    workspaceDependencies: [],
  },
];

export type PackageName =
  | "@malphite/core"
  | "@malphite-tool/cli"
  | "@malphite-tools/utils";
