// Auto generated contend
// DO NOT EDIT THIS FILE MANUALLY

export const PackageList = [
  {
    name: "@mlphite/web",
    path: "packages/frontend/app/web",
    workspaceDependencies: [],
  },
  {
    name: "@malphite/core",
    path: "packages/frontend/core",
    workspaceDependencies: [],
  },
  {
    name: "@types/build-config",
    path: "tools/@types/build-config",
    workspaceDependencies: [],
  },
  {
    name: "@malphite-tool/cli",
    path: "tools/cli",
    workspaceDependencies: ["tools/utils"],
  },
  {
    name: "@malphite-tools/utils",
    path: "tools/utils",
    workspaceDependencies: [],
  },
];

export type PackageName =
  | "@mlphite/web"
  | "@malphite/core"
  | "@types/build-config"
  | "@malphite-tool/cli"
  | "@malphite-tools/utils";
