import { readFileSync, writeFileSync } from "node:fs";
import { Biome, type Configuration } from "@biomejs/js-api/nodejs";
import { type Path, ProjectRoot } from "@malphite-tools/utils/path";
import type { Package } from "@malphite-tools/utils/workspace";
import { pnpmWorkspaces, Workspace } from "@malphite-tools/utils/workspace";
import { applyEdits, modify } from "jsonc-parser";
import { Command } from "./command";

export class InitCommand extends Command {
  static override paths = [["init"], ["i"]];

  async execute() {
    this.generateWorkspaceFiles();
  }

  async generateWorkspaceFiles() {
    this.workspace = new Workspace(pnpmWorkspaces());

    const filesToGenerate: [Path, (prev: string) => string, string?][] = [
      [this.workspace.join("tsconfig.json"), this.genProjectTsConfig, "jsonc"],
      [
        this.workspace
          .getPackage("@malphite-tools/utils")
          .join("src/workspace.gen.ts"),
        this.genWorkspaceInfo,
        "ts",
      ],
      ...this.workspace.packages
        .filter((pkg) => pkg.isTsProject)
        .map(
          (pkg) =>
            [
              pkg.join("tsconfig.json"),
              this.genPackageTsconfig.bind(this, pkg),
              "jsonc",
            ] as [Path, (prev: string) => string, string],
        ),
    ];

    for (const [path, content, extension] of filesToGenerate) {
      const previous = readFileSync(path.value, "utf-8");
      let file = content(previous);

      if (extension) {
        file = this.format(file, extension);
      }

      writeFileSync(path.value, file);
    }
  }

  format(content: string, extension: string) {
    const biome = new Biome();
    const { projectKey } = biome.openProject(ProjectRoot.value);
    const biomeConfigPath = ProjectRoot.join("biome.json").value;

    const biomeConfig = JSON.parse(
      readFileSync(biomeConfigPath, "utf-8"),
    ) as Configuration;
    biome.applyConfiguration(projectKey, biomeConfig);

    const { content: formattedContent } = biome.formatContent(
      projectKey,
      content,
      {
        filePath: `file.${extension}`,
      },
    );
    return formattedContent;
  }

  genWorkspaceInfo = () => {
    const workspaces = pnpmWorkspaces();

    const workspaceNames = workspaces
      .map((item) => item.name)
      .map((name) => `'${name}'`)
      .join(" | ");

    const content = [
      "// Auto generated contend",
      "// DO NOT EDIT THIS FILE MANUALLY",
      "",
      `export const PackageList = ${JSON.stringify(workspaces, null, 2)}`,
      "",
      `export type PackageName = ${workspaceNames}`,
    ];

    return content.join("\n");
  };

  genProjectTsConfig = (prev: string) => {
    return applyEdits(
      prev,
      modify(
        prev,
        ["references"],
        this.workspace.packages
          .filter((pkg) => pkg.isTsProject)
          .map((pkg) => ({ path: pkg.path.relativePath })),
        {},
      ),
    );
  };

  genPackageTsconfig = (_pkg: Package, prev: string) => {
    return applyEdits(
      prev,
      modify(
        prev,
        ["references"],
        this.workspace.packages
          .filter((pkg) => pkg.isTsProject)
          .map((pkg) => ({ path: pkg.path.relativePath })),
        {},
      ),
    );
  };
}
